
name: CI

on:
  workflow_call:
    inputs:
      TEST_ENV_VARS:
        required: false
        type: string


jobs:
  test:
    name: Test
    uses: eitrtechnologies/test-github-actions-central/.github/workflows/test-action.yml@main
    with:
      TEST_ENV_VARS: "${{ inputs.TEST_ENV_VARS }}"
