
name: CI

on:
  workflow_call:
    secrets:
      TEST_ENV_VARS:
        required: false


jobs:
  test:
    name: Test
    uses: eitrtechnologies/test-github-actions-central/.github/workflows/test-action.yml@main
    with:
      TEST_ENV_VARS: ${{ secrets.TEST_ENV_VARS }}
