
name: Testing

on:
  workflow_call:
    secrets:
      TEST_ENV_VARS:
        require: false

jobs:
  Linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false

    steps:
    - name: Decode environment variables for tests
      env:
        TEST_ENV_VARS: ${{ secrets.TEST_ENV_VARS }}
      run: |
        echo "$TEST_ENV_VARS" | base64 -d >> $GITHUB_ENV

    - name: Just testing if the env vars got here
      run: |
        [[ "$EITR_ID" == "hello" ]] && echo "hello"
        [[ "$EITR_SECRET" == "world" ]] && echo "world"
