
name: Testing

on:
  workflow_call:

jobs:
  Linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false

    steps:
    - name: Just testing if the env vars got here
      run: |
        [[ "$EITR_ID" == "hello" ]] && echo "hello"
        [[ "$EITR_SECRET" == "world" ]] && echo "world"
